# Generated by Django 5.2 on 2025-07-25 11:20

import django.db.models.deletion
import django.utils.timezone
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('gestion', '0002_moto_conducteur'),
    ]

    operations = [
        migrations.CreateModel(
            name='Recette',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('date', models.DateField(default=django.utils.timezone.now)),
                ('jour', models.CharField(choices=[('Lundi', 'Lundi'), ('Mardi', 'Mardi'), ('Mercredi', 'Mercredi'), ('Jeudi', 'Jeudi'), ('Vendredi', 'Vendredi'), ('Samedi', 'Samedi')], max_length=10)),
                ('montant', models.DecimalField(decimal_places=2, max_digits=10)),
                ('depense', models.DecimalField(decimal_places=2, max_digits=10)),
                ('conducteur', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='gestion.conducteur')),
            ],
            options={
                'unique_together': {('conducteur', 'date')},
            },
        ),
    ]
