# Generated by Django 5.2 on 2025-08-13 13:32

import django.db.models.deletion
import django.utils.timezone
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('gestion', '0003_recette'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='recette',
            options={'ordering': ['-date']},
        ),
        migrations.AddField(
            model_name='moto',
            name='statut',
            field=models.CharField(choices=[('disponible', 'Disponible'), ('attribuee', 'Attribuée'), ('reparation', 'En réparation')], default='disponible', max_length=20),
        ),
        migrations.CreateModel(
            name='Absence',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('date', models.DateField(default=django.utils.timezone.now)),
                ('raison', models.TextField(blank=True, null=True)),
                ('conducteur', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='gestion.conducteur')),
            ],
        ),
        migrations.CreateModel(
            name='Paiement',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('date_paiement', models.DateField(default=django.utils.timezone.now)),
                ('montant_paye', models.DecimalField(decimal_places=2, max_digits=10)),
                ('periode_debut', models.DateField()),
                ('periode_fin', models.DateField()),
                ('conducteur', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='gestion.conducteur')),
            ],
        ),
    ]
