# Generated by Django 5.2 on 2025-08-16 18:27

import django.db.models.deletion
import django.utils.timezone
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('gestion', '0004_alter_recette_options_moto_statut_absence_paiement'),
    ]

    operations = [
        migrations.CreateModel(
            name='Panne',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('date', models.DateField(default=django.utils.timezone.now)),
                ('description', models.TextField(help_text='Description des réparations ou matériels achetés')),
                ('montant_depense', models.DecimalField(decimal_places=2, help_text='Montant total dépensé', max_digits=10)),
                ('facture', models.FileField(blank=True, help_text='Ajouter un fichier de facture si disponible', null=True, upload_to='factures/')),
                ('admin', models.ForeignKey(help_text='Administrateur ayant enregistré la panne', limit_choices_to={'role': 'admin'}, null=True, on_delete=django.db.models.deletion.SET_NULL, to=settings.AUTH_USER_MODEL)),
                ('moto', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='pannes', to='gestion.moto')),
            ],
            options={
                'ordering': ['-date'],
            },
        ),
        migrations.DeleteModel(
            name='Paiement',
        ),
    ]
