# Generated by Django 5.2 on 2025-10-09 12:36

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('gestion', '0009_reservationrapide'),
    ]

    operations = [
        migrations.AddField(
            model_name='reservationrapide',
            name='destination',
            field=models.CharField(blank=True, max_length=200, null=True),
        ),
        migrations.AddField(
            model_name='reservationrapide',
            name='heure',
            field=models.TimeField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='reservationrapide',
            name='lieu',
            field=models.CharField(blank=True, max_length=200, null=True),
        ),
        migrations.AddField(
            model_name='reservationrapide',
            name='nom',
            field=models.CharField(blank=True, max_length=150, null=True),
        ),
    ]
